//! Integration tests for Makefile CI contract.

use anyhow::{Context, Result};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn test_make_clean_removes_temp_artifacts() -> Result<()> {
    let temp_dir = TempDir::new().context("create temp dir")?;
    let repo_root = temp_dir.path();

    // Create minimal Cargo workspace structure
    std::fs::write(
        repo_root.join("Cargo.toml"),
        r#"[workspace]
members = []
"#,
    )
    .context("write Cargo.toml")?;

    std::fs::write(
        repo_root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n",
    )
    .context("write Cargo.lock")?;

    // Copy Makefile to temp directory
    let makefile_source = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?
        .join("Makefile");
    std::fs::copy(&makefile_source, repo_root.join("Makefile")).context("copy Makefile")?;

    // Create Ralph structure
    let ralph_dir = repo_root.join(".ralph");
    std::fs::create_dir_all(&ralph_dir).context("create .ralph dir")?;

    // Create temp directories with sample files
    std::fs::create_dir_all(ralph_dir.join("cache/plans"))?;
    std::fs::write(ralph_dir.join("cache/test_plan.md"), "test").context("write test plan")?;

    std::fs::create_dir_all(ralph_dir.join("cache/completions"))?;
    std::fs::write(ralph_dir.join("cache/completions/test.json"), "{}")
        .context("write completion signal")?;

    std::fs::create_dir_all(ralph_dir.join("lock"))?;
    std::fs::write(ralph_dir.join("lock/owner"), "test").context("write lock file")?;

    std::fs::create_dir_all(ralph_dir.join("logs"))?;
    std::fs::write(ralph_dir.join("logs/test.log"), "test log").context("write log file")?;

    // Create user data
    std::fs::write(ralph_dir.join("queue.json"), "[]").context("write queue.json")?;
    std::fs::write(ralph_dir.join("done.json"), "[]").context("write done.json")?;
    std::fs::write(ralph_dir.join("config.json"), "{}").context("write config.json")?;

    // Create prompts override
    std::fs::create_dir_all(ralph_dir.join("prompts")).context("create prompts dir")?;
    std::fs::write(ralph_dir.join("prompts/worker.md"), "# override")
        .context("write prompt override")?;

    // Create README
    std::fs::write(ralph_dir.join("README.md"), "# Ralph").context("write README")?;

    // Run make clean
    let status = Command::new("make")
        .arg("clean")
        .current_dir(repo_root)
        .status()
        .context("run make clean")?;
    assert!(status.success(), "make clean should succeed");

    // Verify temp directories removed (except completion signals)
    assert!(
        !ralph_dir.join("cache/plans").exists(),
        "cache plans directory should be removed"
    );
    assert!(
        !ralph_dir.join("cache/test_plan.md").exists(),
        "cache test_plan.md should be removed"
    );
    assert!(
        ralph_dir.join("cache/completions").exists(),
        "completion signals directory should be preserved"
    );
    assert!(
        ralph_dir.join("cache/completions/test.json").exists(),
        "completion signal should be preserved"
    );
    assert!(
        !ralph_dir.join("lock").exists(),
        "lock directory should be removed"
    );
    assert!(
        !ralph_dir.join("logs").exists(),
        "logs directory should be removed"
    );

    // Verify user data preserved
    assert!(
        ralph_dir.join("queue.json").exists(),
        "queue.json should be preserved"
    );
    assert!(
        ralph_dir.join("done.json").exists(),
        "done.json should be preserved"
    );
    assert!(
        ralph_dir.join("config.json").exists(),
        "config.json should be preserved"
    );
    assert!(
        ralph_dir.join("prompts").exists(),
        "prompts directory should be preserved"
    );
    assert!(
        ralph_dir.join("prompts/worker.md").exists(),
        "prompt override file should be preserved"
    );
    assert!(
        ralph_dir.join("README.md").exists(),
        "README.md should be preserved"
    );

    Ok(())
}
