//! Integration tests for Makefile CI contract.

use anyhow::{Context, Result};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn test_make_clean_removes_temp_artifacts() -> Result<()> {
    let temp_dir = TempDir::new().context("create temp dir")?;
    let repo_root = temp_dir.path();

    // Create minimal Cargo workspace structure
    std::fs::write(
        repo_root.join("Cargo.toml"),
        r#"[workspace]
members = []
"#,
    )
    .context("write Cargo.toml")?;

    std::fs::write(
        repo_root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n",
    )
    .context("write Cargo.lock")?;

    // Copy Makefile to temp directory
    let makefile_source = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?
        .join("Makefile");
    std::fs::copy(&makefile_source, repo_root.join("Makefile")).context("copy Makefile")?;

    // Create Ralph structure
    let ralph_dir = repo_root.join(".ralph");
    std::fs::create_dir_all(&ralph_dir).context("create .ralph dir")?;

    // Create temp directories with sample files
    std::fs::create_dir_all(ralph_dir.join("cache/plans"))?;
    std::fs::write(ralph_dir.join("cache/test_plan.md"), "test").context("write test plan")?;

    std::fs::create_dir_all(ralph_dir.join("cache/completions"))?;
    std::fs::write(ralph_dir.join("cache/completions/test.json"), "{}")
        .context("write completion signal")?;

    std::fs::create_dir_all(ralph_dir.join("lock"))?;
    std::fs::write(ralph_dir.join("lock/owner"), "test").context("write lock file")?;

    std::fs::create_dir_all(ralph_dir.join("logs"))?;
    std::fs::write(ralph_dir.join("logs/test.log"), "test log").context("write log file")?;

    // Create user data
    std::fs::write(ralph_dir.join("queue.json"), "[]").context("write queue.json")?;
    std::fs::write(ralph_dir.join("done.json"), "[]").context("write done.json")?;
    std::fs::write(ralph_dir.join("config.json"), "{}").context("write config.json")?;

    // Create prompts override
    std::fs::create_dir_all(ralph_dir.join("prompts")).context("create prompts dir")?;
    std::fs::write(ralph_dir.join("prompts/worker.md"), "# override")
        .context("write prompt override")?;

    // Create README
    std::fs::write(ralph_dir.join("README.md"), "# Ralph").context("write README")?;

    // Run make clean
    let status = Command::new("make")
        .arg("clean")
        .current_dir(repo_root)
        .status()
        .context("run make clean")?;
    assert!(status.success(), "make clean should succeed");

    // Verify temp directories removed (except completion signals)
    assert!(
        !ralph_dir.join("cache/plans").exists(),
        "cache plans directory should be removed"
    );
    assert!(
        !ralph_dir.join("cache/test_plan.md").exists(),
        "cache test_plan.md should be removed"
    );
    assert!(
        ralph_dir.join("cache/completions").exists(),
        "completion signals directory should be preserved"
    );
    assert!(
        ralph_dir.join("cache/completions/test.json").exists(),
        "completion signal should be preserved"
    );
    assert!(
        !ralph_dir.join("lock").exists(),
        "lock directory should be removed"
    );
    assert!(
        !ralph_dir.join("logs").exists(),
        "logs directory should be removed"
    );

    // Verify user data preserved
    assert!(
        ralph_dir.join("queue.json").exists(),
        "queue.json should be preserved"
    );
    assert!(
        ralph_dir.join("done.json").exists(),
        "done.json should be preserved"
    );
    assert!(
        ralph_dir.join("config.json").exists(),
        "config.json should be preserved"
    );
    assert!(
        ralph_dir.join("prompts").exists(),
        "prompts directory should be preserved"
    );
    assert!(
        ralph_dir.join("prompts/worker.md").exists(),
        "prompt override file should be preserved"
    );
    assert!(
        ralph_dir.join("README.md").exists(),
        "README.md should be preserved"
    );

    Ok(())
}

/// Extract the ordered list of targets from the `ci:` recipe in a Makefile.
/// Handles both modern format (dependencies on the same line) and legacy format
/// (separate $(MAKE) invocations within the target body).
fn extract_make_ci_steps(makefile: &str) -> Result<Vec<String>> {
    let mut in_ci = false;
    let mut steps = Vec::new();

    for line in makefile.lines() {
        // Enter `ci:` target
        if !in_ci {
            if let Some(colon_idx) = line.find("ci:") {
                in_ci = true;
                // Modern format: extract dependencies from the same line after "ci:"
                let deps_part = &line[colon_idx + 3..];
                let deps: Vec<String> = deps_part
                    .split_whitespace()
                    .map(|s| s.to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
                steps.extend(deps);
            }
            continue;
        }

        // If another top-level target begins, stop
        let is_top_level = !line.starts_with('\t') && !line.starts_with(' ');
        if is_top_level {
            let t = line.trim();
            if !t.is_empty() && !t.starts_with('#') && t.ends_with(':') {
                break;
            }
        }

        // Legacy format: look for $(MAKE) <target> invocations
        if let Some(idx) = line.find("$(MAKE) ") {
            let rest = &line[idx + "$(MAKE) ".len()..];
            let target = rest
                .split_whitespace()
                .next()
                .context("parse $(MAKE) <target> in ci recipe")?;
            steps.push(target.to_string());
        }
    }

    anyhow::ensure!(
        !steps.is_empty(),
        "failed to extract any ci steps from Makefile"
    );
    Ok(steps)
}

/// Extract one target block (`target: ...` plus recipe lines) from a Makefile.
fn extract_target_block(makefile: &str, target: &str) -> Result<String> {
    let header = format!("{target}:");
    let mut block_lines = Vec::new();
    let mut in_target = false;

    for line in makefile.lines() {
        if !in_target {
            if line.starts_with(&header) {
                in_target = true;
                block_lines.push(line.to_string());
            }
            continue;
        }

        let is_top_level = !line.starts_with('\t') && !line.starts_with(' ');
        if is_top_level {
            let trimmed = line.trim();
            if let Some(colon_idx) = trimmed.find(':') {
                // Skip variable assignments like `FOO := bar`.
                let is_assignment = trimmed.as_bytes().get(colon_idx + 1) == Some(&b'=');
                if !is_assignment && !trimmed.starts_with('#') && !trimmed.starts_with(".PHONY") {
                    break;
                }
            }
        }

        block_lines.push(line.to_string());
    }

    anyhow::ensure!(
        !block_lines.is_empty(),
        "failed to extract target block for `{target}`"
    );
    Ok(block_lines.join("\n"))
}

#[test]
fn test_makefile_ci_includes_type_check_in_order() -> Result<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?;
    let makefile = std::fs::read_to_string(repo_root.join("Makefile")).context("read Makefile")?;

    assert!(
        makefile.contains("type-check:"),
        "Makefile should define a type-check target"
    );

    let steps = extract_make_ci_steps(&makefile).context("extract Makefile ci steps")?;

    // Find indices of format, type-check, lint
    let format_pos = steps.iter().position(|s| s == "format");
    let type_check_pos = steps.iter().position(|s| s == "type-check");
    let lint_pos = steps.iter().position(|s| s == "lint");

    assert!(format_pos.is_some(), "format step should be in ci target");
    assert!(
        type_check_pos.is_some(),
        "type-check step should be in ci target"
    );
    assert!(lint_pos.is_some(), "lint step should be in ci target");

    let format_idx = format_pos.unwrap();
    let type_check_idx = type_check_pos.unwrap();
    let lint_idx = lint_pos.unwrap();

    assert!(
        format_idx < type_check_idx && type_check_idx < lint_idx,
        "type-check should run after format and before lint in ci target"
    );

    Ok(())
}

#[test]
fn test_contributing_ci_step_list_matches_makefile_ci_recipe() -> Result<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?;

    let makefile = std::fs::read_to_string(repo_root.join("Makefile")).context("read Makefile")?;
    let contributing = std::fs::read_to_string(repo_root.join("CONTRIBUTING.md"))
        .context("read CONTRIBUTING.md")?;

    let make_steps = extract_make_ci_steps(&makefile).context("extract Makefile ci steps")?;
    let pipeline = make_steps.join(" → ");

    assert!(
        contributing.contains(&pipeline),
        "CONTRIBUTING.md CI pipeline drifted from Makefile `ci` recipe.\n\
         Expected to find: {}\n",
        pipeline
    );

    Ok(())
}

#[test]
fn test_gemini_ci_step_list_matches_makefile_ci_recipe() -> Result<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?;

    let makefile = std::fs::read_to_string(repo_root.join("Makefile")).context("read Makefile")?;
    let gemini = std::fs::read_to_string(repo_root.join("GEMINI.md")).context("read GEMINI.md")?;

    let make_steps = extract_make_ci_steps(&makefile).context("extract Makefile ci steps")?;
    let pipeline = make_steps.join(" → ");

    assert!(
        gemini.contains(&pipeline),
        "GEMINI.md CI pipeline drifted from Makefile `ci` recipe.\n\
         Expected to find: {}\n",
        pipeline
    );

    Ok(())
}

#[test]
fn test_lint_is_non_mutating_and_lint_fix_is_opt_in() -> Result<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?;
    let makefile = std::fs::read_to_string(repo_root.join("Makefile")).context("read Makefile")?;

    let lint_block = extract_target_block(&makefile, "lint").context("extract lint block")?;
    assert!(
        lint_block.contains("cargo clippy"),
        "lint target should run cargo clippy"
    );
    assert!(
        !lint_block.contains("--fix"),
        "lint target must be non-mutating"
    );

    let lint_fix_block =
        extract_target_block(&makefile, "lint-fix").context("extract lint-fix block")?;
    assert!(
        lint_fix_block.contains("cargo clippy"),
        "lint-fix target should run cargo clippy"
    );
    assert!(
        lint_fix_block.contains("--fix"),
        "lint-fix target should include --fix"
    );

    Ok(())
}

#[test]
fn test_macos_targets_gate_with_preflight_and_isolate_derived_data() -> Result<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .context("resolve repo root")?;
    let makefile = std::fs::read_to_string(repo_root.join("Makefile")).context("read Makefile")?;

    assert!(
        makefile.contains("macos-preflight:"),
        "Makefile should define macos-preflight target"
    );
    assert!(
        makefile.contains("macos-build:\n\t@$(MAKE) --no-print-directory macos-preflight"),
        "macos-build should run macos-preflight first"
    );
    assert!(
        makefile.contains("macos-test:\n\t@$(MAKE) --no-print-directory macos-preflight"),
        "macos-test should run macos-preflight first"
    );
    assert!(
        makefile.contains("macos-ci: macos-preflight"),
        "macos-ci should depend on macos-preflight"
    );
    assert!(
        makefile.contains("derived_data_path=\"$(XCODE_DERIVED_DATA_ROOT)/build\""),
        "macos-build should use an isolated build DerivedData path"
    );
    assert!(
        makefile.contains("derived_data_path=\"$(XCODE_DERIVED_DATA_ROOT)/test\""),
        "macos-test should use an isolated test DerivedData path"
    );
    assert!(
        makefile.contains("rm -rf \"$$derived_data_path\""),
        "macOS targets should clear DerivedData before running xcodebuild"
    );

    Ok(())
}
