//! Clean-target smoke coverage for Makefile contracts.
//!
//! Purpose:
//! - Clean-target smoke coverage for Makefile contracts.
//!
//! Responsibilities:
//! - Verify `make clean` removes temp/runtime artifacts.
//! - Verify `make clean` preserves user-owned Ralph data.
//! - Keep filesystem smoke coverage isolated from parser assertions.
//!
//! Not handled here:
//! - CI dependency-sequence parsing.
//! - Documentation and routing contracts.
//!
//!
//! Usage:
//! - Used through the crate module tree or integration test harness.
//!
//! Invariants/assumptions:
//! - The temp workspace copies only the Makefile under test.
//! - GNU Make availability is validated through the suite support helper.

use anyhow::{Context, Result};
use tempfile::TempDir;

use super::makefile_ci_contract_test_support::{repo_root, resolve_make_command};

#[test]
fn test_make_clean_removes_temp_artifacts() -> Result<()> {
    let temp_dir = TempDir::new().context("create temp dir")?;
    let repo_dir = temp_dir.path();

    std::fs::write(repo_dir.join("Cargo.toml"), "[workspace]\nmembers = []\n")
        .context("write Cargo.toml")?;
    std::fs::write(
        repo_dir.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n",
    )
    .context("write Cargo.lock")?;

    let makefile_source = repo_root()?.join("Makefile");
    std::fs::copy(&makefile_source, repo_dir.join("Makefile")).context("copy Makefile")?;

    let ralph_dir = repo_dir.join(".ralph");
    std::fs::create_dir_all(&ralph_dir).context("create .ralph dir")?;
    std::fs::create_dir_all(ralph_dir.join("cache/plans"))?;
    std::fs::write(ralph_dir.join("cache/test_plan.md"), "test").context("write test plan")?;
    std::fs::create_dir_all(ralph_dir.join("lock"))?;
    std::fs::write(ralph_dir.join("lock/owner"), "test").context("write lock file")?;
    std::fs::create_dir_all(ralph_dir.join("logs"))?;
    std::fs::write(ralph_dir.join("logs/test.log"), "test log").context("write log file")?;
    std::fs::write(ralph_dir.join("queue.json"), "[]").context("write queue.json")?;
    std::fs::write(ralph_dir.join("done.json"), "[]").context("write done.json")?;
    std::fs::write(ralph_dir.join("config.json"), "{}").context("write config.json")?;
    std::fs::create_dir_all(ralph_dir.join("prompts")).context("create prompts dir")?;
    std::fs::write(ralph_dir.join("prompts/worker.md"), "# override")
        .context("write prompt override")?;
    std::fs::write(ralph_dir.join("README.md"), "# Ralph").context("write README")?;

    let make_cmd = resolve_make_command().context("resolve make command")?;
    let status = std::process::Command::new(&make_cmd)
        .arg("clean")
        .current_dir(repo_dir)
        .status()
        .with_context(|| format!("run {make_cmd} clean"))?;
    assert!(status.success(), "{make_cmd} clean should succeed");

    assert!(
        !ralph_dir.join("cache/plans").exists(),
        "cache plans directory should be removed"
    );
    assert!(
        !ralph_dir.join("cache/test_plan.md").exists(),
        "cache test_plan.md should be removed"
    );
    assert!(
        !ralph_dir.join("lock").exists(),
        "lock directory should be removed"
    );
    assert!(
        !ralph_dir.join("logs").exists(),
        "logs directory should be removed"
    );
    assert!(
        ralph_dir.join("queue.json").exists(),
        "queue.json should be preserved"
    );
    assert!(
        ralph_dir.join("done.json").exists(),
        "done.json should be preserved"
    );
    assert!(
        ralph_dir.join("config.json").exists(),
        "config.json should be preserved"
    );
    assert!(
        ralph_dir.join("prompts").exists(),
        "prompts directory should be preserved"
    );
    assert!(
        ralph_dir.join("prompts/worker.md").exists(),
        "prompt override file should be preserved"
    );
    assert!(
        ralph_dir.join("README.md").exists(),
        "README.md should be preserved"
    );

    Ok(())
}
